export const ADD_TO_CURRENT_SONG = 'ADD_TO_CURRENT_SONG';
export const IS_CONNECTED = 'IS_CONNECTED'
export const GET_USER = 'GET_USER'
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
export const GET_PLAYLISTS = 'GET_PLAYLISTS'
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST'
export const GET_SONGS_TO_PLAYLIST = 'GET_SONGS_TO_PLAYLIST'