export const HOME = '/'
export const LOGIN = '/login'
export const APP = '/app'
    export const RESULTS = '/app/results'
    export const CURRENTLIST = '/app/current-list'
    export const LISTPLAYLISTS = '/app/list-playlists'
    export const DETAILPLAYLIST = '/app/detail-playlist'
    export const MOBILEPLAYER = '/app/mobile-player'
